
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cewxnkpihtujqbwbzjcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNld3hua3BpaHR1anFid2J6amN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NzM4ODksImV4cCI6MjA1NDU0OTg4OX0.FfTnn08pR4TlBUEGx1ofIrt4PEP9w_XW5hYx0r1mfDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'swipescholar-auth',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
